### ISSUE TITLE
Error when running the JPA example from the official website?

### ISSUE THREAD

**Issue by z589533** [rapidoid/rapidoid#124]
![image](https://user-images.githubusercontent.com/12063612/28055836-431a018c-664d-11e7-9983-eb4043f288a7.png)

**Comment by z589533** [comment]
INFO ] 2017-07-11 15:24:46,320 - - [server1] [org.rapidoid.http.impl.HttpRoutesImpl] GET /books                                     | setup = main | roles = [] | transaction = NONE | mvc = false | cacheTTL = 0 
 [INFO ] 2017-07-11 15:24:46,330 - - [server1] [org.rapidoid.http.impl.HttpRoutesImpl] POST /books                                    | setup = main | roles = [] | transaction = NONE | mvc = false | cacheTTL = 0 
 [INFO ] 2017-07-11 15:24:46,330 - - [server1] [org.rapidoid.setup.App] Successfully restarted the application! 
 [ERROR] 2017-07-11 15:24:46,880 - - [executor2] [org.rapidoid.http.impl.lowlevel.LowLevelHttpIO] Error occurred when handling request! | error = java.lang.RuntimeException: Error occurred in the EntityManagerFactory provider!
java.lang.RuntimeException: Error occurred in the EntityManagerFactory provider!
	at org.rapidoid.u.U.rte(U.java:426)
	at org.rapidoid.setup.CustomizableSetupAwarePersisterProvider.openPersister(CustomizableSetupAwarePersisterProvider.java:64)
	at org.rapidoid.ctx.Ctxs.createPersister(Ctxs.java:111)
	at org.rapidoid.ctx.Ctx.persister(Ctx.java:88)
	at org.rapidoid.jpa.JPA.tool(JPA.java:61)
	at org.rapidoid.jpa.JPA.of(JPA.java:287)
	at com.bluepay.oauth.start.RapidoidAoolication.lambda$main$0(RapidoidAoolication.java:24)
	at org.rapidoid.http.handler.optimized.CallableHttpHandler.handleReq(CallableHttpHandler.java:47)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.handleReqAndPostProcess(AbstractDecoratingHttpHandler.java:313)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.handleReqMaybeInTx(AbstractDecoratingHttpHandler.java:245)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler.access$700(AbstractDecoratingHttpHandler.java:49)
	at org.rapidoid.http.handler.AbstractDecoratingHttpHandler$3.run(AbstractDecoratingHttpHandler.java:211)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: JPA.emf must NOT be null!
	at org.rapidoid.u.U.illegal(U.java:442)
	at org.rapidoid.u.U.notNull(U.java:489)
	at org.rapidoid.jpa.JPA.provideEmf(JPA.java:266)
	at org.rapidoid.http.customize.defaults.DefaultEntityManagerFactoryProvider.getEntityManagerFactory(DefaultEntityManagerFactoryProvider.java:38)
	at org.rapidoid.setup.CustomizableSetupAwarePersisterProvider.openPersister(CustomizableSetupAwarePersisterProvider.java:62)
	... 14 more

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/28055874-724730c4-664d-11e7-9a9c-00420b974e60.png)

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/28055888-81fa9fc4-664d-11e7-82e1-7c043c13a03c.png)

**Comment by nmihajlovski** [comment]
Sorry, I wasn't able to reproduce this error.

Can you please provide more information about how to reproduce this bug? (Rapidoid version used, JDK version, does it happen only after code change / application reloading?)

**Comment by emi-silva** [comment]
I'm facing the same issue.

Here's my main file `Debo.java`:
```
package com.github.emi_silva.debo;

import org.rapidoid.setup.On;
import org.rapidoid.u.U;

import javax.validation.Valid;
import org.rapidoid.jpa.JPA;
import org.rapidoid.setup.App;

/**
 * Rapidoid with JPA
 *
 */
public class Debo 
{
    public static void main( String[] args )
    {
	App.bootstrap(args).jpa();
	On.get("/books").json(() -> JPA.of(Book.class).all());
	On.post("/books").json((@Valid Book b) -> JPA.save(b));

	On.get("/size").json((String msg) -> msg.length());
	On.get("/hello").json(() -> U.map("msg", "Hello, world!"));
    }
}
```

Here's `Book.java`:
```
package com.github.emi_silva.debo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

@Entity
public class Book {
    
    @Id
    @GeneratedValue
    public Long id;

    @NotNull
    public String title;

    public int year;
}
```

When I deploy the app everything seems to work fine:
```
$ mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building debo 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ debo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/emilio/code/debo/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ debo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ debo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/emilio/code/debo/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ debo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ debo ---
[INFO] Surefire report directory: /home/emilio/code/debo/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.emi_silva.debo.DeboTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ debo ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.301 s
[INFO] Finished at: 2018-09-09T14:41:59-05:00
[INFO] Final Memory: 14M/304M
[INFO] ------------------------------------------------------------------------
```

When I execute the app, still things seem OK:

```
$ mvn exec:java
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building debo 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ debo >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ debo <<<
[INFO] 
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ debo ---
INFO | 09/Sep/2018 14:44:40:314 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.config.RapidoidInitializer | Starting Rapidoid v5.5.5, built on 2018-05-27 15:45 UTC
INFO | 09/Sep/2018 14:44:40:315 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.config.RapidoidInitializer | System info | os = Linux | java = 1.8.0_172 | process = 14722@nietzsche | max memory = 455 MB | dir = /home/emilio/code/debo
INFO | 09/Sep/2018 14:44:40:429 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.env.Environment | No profiles were specified, activating 'default' profile
INFO | 09/Sep/2018 14:44:40:432 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.env.Environment | No production/dev/test mode was configured, inferring mode | mode = PRODUCTION
INFO | 09/Sep/2018 14:44:40:432 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.env.Environment | Initialized environment | mode = PRODUCTION | profiles = [default, production]
INFO | 09/Sep/2018 14:44:40:588 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.config.ConfigImpl | Loaded configuration | namespace = config | files = [built-in-config.yml, built-in-config-default.yml, config.yml]
INFO | 09/Sep/2018 14:44:40:589 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.setup.App | Inferred application root | main = com.github.emi_silva.debo.Debo | package = com.github.emi_silva.debo
INFO | 09/Sep/2018 14:44:40:593 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.scan.ClasspathScanner | Scanning classpath | annotated = [@Controller, @Service, @Run, @Named, @Singleton] | packages = [com.github.emi_silva.debo]
INFO | 09/Sep/2018 14:44:40:594 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.scan.ClasspathScanner | Finished classpath scan | time = 1ms | searched = 0 | found = []
INFO | 09/Sep/2018 14:44:40:662 | server | org.rapidoid.net.impl.RapidoidServerLoop | Starting server | address = 0.0.0.0 | port = 8080 | I/O workers = 8 | sync = true | accept = non-blocking
INFO | 09/Sep/2018 14:44:41:070 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.setup.Setup | Server has started | setup = main | home = http://localhost:8080
INFO | 09/Sep/2018 14:44:41:070 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.setup.Setup | Static resources will be served from the following locations | setup = main | locations = [static, default/static]
INFO | 09/Sep/2018 14:44:41:071 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.setup.App | Ready.
INFO | 09/Sep/2018 14:44:41:084 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.jdbc.JdbcClient | Initializing JDBC connection pool with Hikari | url = jdbc:postgresql://localhost:5432/debo | driver = org.postgresql.Driver | username = emilio | password = *****
[com.github.emi_silva.debo.Debo.main()] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[com.github.emi_silva.debo.Debo.main()] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
INFO | 09/Sep/2018 14:44:41:209 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.jdbc.JdbcClient | Initialized JDBC API | url = jdbc:postgresql://localhost:5432/debo | driver = org.postgresql.Driver | username = emilio | password = ***** | dataSource = HikariDataSource
INFO | 09/Sep/2018 14:44:41:209 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.util.Msc | --------------------------------
INFO | 09/Sep/2018 14:44:41:209 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.util.Msc | Bootstrapping JPA (Hibernate)...
INFO | 09/Sep/2018 14:44:41:209 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.util.Msc | --------------------------------
INFO | 09/Sep/2018 14:44:41:210 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.scan.ClasspathScanner | Scanning classpath | annotated = [@Entity] | packages = [com.github.emi_silva.debo]
INFO | 09/Sep/2018 14:44:41:210 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.scan.ClasspathScanner | Finished classpath scan | time = 0ms | searched = 0 | found = []
INFO | 09/Sep/2018 14:44:41:211 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.jpa.JPAUtil | Didn't find JPA entities, canceling JPA/Hibernate setup!
INFO | 09/Sep/2018 14:44:41:214 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.http.impl.HttpRoutesImpl | GET /books                                     | setup = main | roles = [] | transaction = NONE | mvc = false | cacheTTL = 0
INFO | 09/Sep/2018 14:44:41:245 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.http.impl.HttpRoutesImpl | POST /books                                    | setup = main | roles = [] | transaction = NONE | mvc = false | cacheTTL = 0
INFO | 09/Sep/2018 14:44:41:247 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.http.impl.HttpRoutesImpl | GET /size                                      | setup = main | roles = [] | transaction = NONE | mvc = false | cacheTTL = 0
INFO | 09/Sep/2018 14:44:41:248 | com.github.emi_silva.debo.Debo.main() | org.rapidoid.http.impl.HttpRoutesImpl | GET /hello                                     | setup = main | roles = [] | transaction = NONE | mvc = false | cacheTTL = 0
```

When I request a different resource, everything works fine:
```
$ http GET http://localhost:8080/hello
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 23
Content-Type: application/json
Date: Sun, 09 Sep 2018 19:47:38 GMT
Server: Rapidoid

{
    "msg": "Hello, world!"
}
```

However, when I request `/books` things go awry:
```
$ http GET http://localhost:8080/books
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 81
Content-Type: application/json
Date: Sun, 09 Sep 2018 19:48:40 GMT
Server: Rapidoid

{
    "code": 500,
    "error": "JPA.emf must NOT be null!",
    "status": "Internal Server Error"
}
```

It doesn't matter if I perform a GET or a POST request:
```
$ http POST http://localhost:8080/books '{"id":1 "title":"hey" year:2016}'
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 81
Content-Type: application/json
Date: Sun, 09 Sep 2018 19:50:12 GMT
Server: Rapidoid

{
    "code": 500,
    "error": "JPA.emf must NOT be null!",
    "status": "Internal Server Error"
}
```
This happens every time I perform a request.

Here's my `config.yml`:
```
jdbc:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/debo
  username: emilio
  password: [edited]
  port: 5432
  options: loglevel=1

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
```

My database exists, though it has no tables:
```
$ psql -d debo
psql (10.4)
Type "help" for help.

debo=# \dt
Did not find any relations.
```

Here's the relevant part of my `pom.xml`:

    <dependency>
      <groupId>org.rapidoid</groupId>
      <artifactId>rapidoid-http-server</artifactId>
      <version>5.5.5</version>
    </dependency>
    <dependency>
      <groupId>javax.persistence</groupId>
      <artifactId>persistence-api</artifactId>
      <version>1.0.2</version>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
      <version>2.0.1.Final</version>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.2.5</version>
    </dependency>
    <dependency>
      <groupId>com.zaxxer</groupId>
      <artifactId>HikariCP</artifactId>
      <version>2.7.8</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-core</artifactId>
      <version>5.3.6.Final</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>1.8.0-beta2</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>1.8.0-beta2</version>
    </dependency>

My JDK version:

    $ java -version
    openjdk version "1.8.0_172"
    OpenJDK Runtime Environment (build 1.8.0_172-b11)
    OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)

**Comment by sysmat** [comment]
Same here

```
Exception in thread "main" java.lang.IllegalArgumentException: emf must NOT be null!
	at org.rapidoid.u.U.illegal(U.java:443)
	at org.rapidoid.u.U.notNull(U.java:490)
	at org.rapidoid.jpa.JPAUtil.emf(JPAUtil.java:167)
	at org.rapidoid.jpa.JPAUtil.bootstrapJPA(JPAUtil.java:115)
	at org.rapidoid.jpa.JPAUtil.bootstrap(JPAUtil.java:84)
	at org.rapidoid.jpa.JPA.bootstrap(JPA.java:199)
	at org.rapidoid.setup.AppBootstrap$2.bootstrap(AppBootstrap.java:48)
	at org.rapidoid.setup.ServiceBootstrap.run(ServiceBootstrap.java:40)
	at org.rapidoid.setup.AppBootstrap.jpa(AppBootstrap.java:157)
	at rapidoid.Main.main(Main.java:14)

```
