### ISSUE TITLE
Couldn't retrieve the parameter names

### ISSUE THREAD

**Issue by ivanviragine** [rapidoid/rapidoid#132]
Hi!

A strange "Couldn't retrieve the parameter names" exception is showing when using this simple construction:

```
	public static void main(String[] args) throws Exception {
		OpenGraphService openGraphService = OpenGraphService.instance();

//		On.get("/opengraph/").json((String url) -> OpenGraphService.instance().getOpenGraphObjectFromUrl(url));
		On.get("/opengraph/").json((String url) -> openGraphService.getOpenGraphObjectFromUrl(url));
		
	}
```

When directly calling "OpenGraphService.instance().getOpenGraphObjectFromUrl(url)" (commented) everything works ok, but when calling "openGraphService.getOpenGraphObjectFromUrl(url)", I'm getting: 

```
Exception in thread "main" java.lang.IllegalArgumentException: Couldn't retrieve the parameter names! Please report this problem. You can explicitly specify the names using @Param("thename"), or configure the option '-parameters' on the Java 8 compiler.
	at org.rapidoid.u.U.illegal(U.java:442)
	at org.rapidoid.u.U.must(U.java:447)
	at org.rapidoid.cls.Cls.getMethodParameterNames(Cls.java:1222)
	at org.rapidoid.cls.Cls.getLambdaParameterNames(Cls.java:1241)
	at org.rapidoid.http.handler.lambda.NParamMethodHandler.<init>(NParamMethodHandler.java:57)
	at org.rapidoid.http.handler.lambda.NParamLambdaHandler.<init>(NParamLambdaHandler.java:36)
	at org.rapidoid.http.handler.lambda.OneParamLambdaHandler.<init>(OneParamLambdaHandler.java:40)
	at org.rapidoid.setup.HttpHandlers.from(HttpHandlers.java:69)
	at org.rapidoid.setup.HttpHandlers.register(HttpHandlers.java:125)
	at org.rapidoid.setup.OnRoute.json(OnRoute.java:198)
```

Any clues?

**Comment by nmihajlovski** [comment]
Hi, thanks for reporting this!

It is hard to retrieve the parameter names in a robust way, since the bytecode depends on the compiler used (e.g. the behavior might be different when running through the IDE vs. running through Maven, depending on the compiler).

Can you please provide more information about how to reproduce this bug (JDK version, compiler used, exact Maven dependencies for the example)?
