### ISSUE TITLE
Automatic Hot Reload Fails in Eclipse

### ISSUE THREAD

**Issue by zaaxch** [rapidoid/rapidoid#150]
I am currently working on a Java project in Eclipse with "rapidoid-web" as a Maven dependency. I am using the simple example from [here](http://www.rapidoid.org/web.html).

```
public class Root {
    public static void main(String[] args) {
        App.bootstrap(args);
    }
}
```

```
@Controller
public class Authentication {
    @GET
    public String hello() {
        return "Hello, world!";
    }
}
```

When I change some code and save it, the watcher logs `watcher1 | org.rapidoid.setup.App | Detected class or resource changes`, but when I go to refresh the page the server throws the following:

```
server3 | org.rapidoid.net.impl.RapidoidWorker | Failed to process message! | type = java.lang.RuntimeException | message = Cannot statically invoke method 'main' with args: [[]]
java.lang.RuntimeException: Cannot statically invoke method 'main' with args: [[]]
	at org.rapidoid.u.U.rte(U.java:426)
	at org.rapidoid.u.U.rte(U.java:438)
	at org.rapidoid.cls.Cls.invokeStatic(Cls.java:314)
	at org.rapidoid.util.Msc.invokeMain(Msc.java:799)
	at org.rapidoid.setup.App.restartApp(App.java:223)
	at org.rapidoid.setup.App.restartIfDirty(App.java:262)
	at org.rapidoid.setup.AppRestartProcessor.onRequest(AppRestartProcessor.java:41)
	at org.rapidoid.http.FastHttpProtocol.process(FastHttpProtocol.java:58)
	at org.rapidoid.net.impl.RapidoidWorker.processNext(RapidoidWorker.java:268)
	at org.rapidoid.net.impl.RapidoidWorker.processMsgs(RapidoidWorker.java:213)
	at org.rapidoid.net.impl.RapidoidWorker.process(RapidoidWorker.java:205)
	at org.rapidoid.net.impl.RapidoidWorker.readOP(RapidoidWorker.java:157)
	at org.rapidoid.net.impl.AbstractEventLoop.processKey(AbstractEventLoop.java:92)
	at org.rapidoid.net.impl.AbstractEventLoop.insideLoop(AbstractEventLoop.java:145)
	at org.rapidoid.net.impl.AbstractLoop.run(AbstractLoop.java:70)
	at org.rapidoid.net.impl.RapidoidWorkerThread.run(RapidoidWorkerThread.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.rapidoid.cls.Cls.invokeStatic(Cls.java:308)
	... 13 more
Caused by: java.lang.IllegalArgumentException: The application was already started!
	at org.rapidoid.u.U.illegal(U.java:442)
	at org.rapidoid.u.U.must(U.java:447)
	at org.rapidoid.setup.AppStarter.startUp(AppStarter.java:44)
	at org.rapidoid.setup.App.bootstrap(App.java:104)
	at org.ruxim.birdr.Root.main(Root.java:15)
        ... 18 more
```

**Comment by javasn** [comment]
Same problem in netbeans with rapidoid v5.4.6.
But there's no problem with rapidoid v5.4.5.

**Comment by nmihajlovski** [comment]
Thanks for reporting, I am working on this now...
