### ISSUE TITLE
JDK9 @Valid not working

### ISSUE THREAD

**Issue by mikko-apo** [rapidoid/rapidoid#155]
I followed the example at http://www.rapidoid.org/restful-services-with-lambda-handlers-jpa-jackson-and-bean-validation.html 

I was using JDK9 (MacOs High Sierra, java build 9+181) and  Rapidoid-quick 5.5.0.

@Valid doesn't work, instead a Book with null title is created when POSTing with

`curl http://localhost:8080/books -d '{}' -H "Content-Type: application/json"`

Using the command line switch --illegal-access=debug provides following stacktrace when starting the application:

`WARNING: Illegal reflective access by org.rapidoid.beany.BeanProp (file:/Users/apo/.m2/repository/org/rapidoid/rapidoid-commons/5.5.0/rapidoid-commons-5.5.0.jar) to method java.lang.reflect.Parameter.getRealName()
	at org.rapidoid.beany.BeanProp.init(BeanProp.java:85)
	at org.rapidoid.beany.Beany$1.map(Beany.java:64)
	at org.rapidoid.beany.Beany$1.map(Beany.java:55)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:51)
	at org.rapidoid.beany.Beany.property(Beany.java:213)
	at org.rapidoid.beany.Beany.getPropValue(Beany.java:399)
	at org.rapidoid.cls.Cls.getMethodParameterNames(Cls.java:1156)
	at org.rapidoid.cls.Cls.getLambdaParameterNames(Cls.java:1248)
	at org.rapidoid.http.handler.lambda.NParamMethodHandler.<init>(NParamMethodHandler.java:58)
	at org.rapidoid.http.handler.lambda.NParamLambdaHandler.<init>(NParamLambdaHandler.java:37)
	at org.rapidoid.http.handler.lambda.TwoParamLambdaHandler.<init>(TwoParamLambdaHandler.java:41)
	at org.rapidoid.setup.HttpHandlers.from(HttpHandlers.java:83)
	at org.rapidoid.setup.HttpHandlers.register(HttpHandlers.java:126)
	at org.rapidoid.setup.OnRoute.json(OnRoute.java:206)
	at apo.Main.main(Main.java:19)
02:17:06.543 [main] INFO  o.rapidoid.http.impl.HttpRoutesImpl - POST /books                                    | setup = main | roles = [] | transaction = NONE | mvc = false | cacheTTL = 0
`

**Main.java**

import org.rapidoid.annotation.Valid;
import org.rapidoid.setup.App;
import org.rapidoid.setup.On;

public class Main {
    public static void main(String[] args) {
        App.bootstrap(args); // bootstrap JPA
        On.post("/books").json((@Valid Book b) -> b); // insert new book if valid
    }
}

**Book.java**

import javax.validation.constraints.NotNull;

public class Book {
    public Book() {
    }
    public Book(String title, int year) {
        this.title = title;
        this.year = year;
    }
    @NotNull
    public String title;
    public int year;
}

Switching to JDK8 fixes the issue.

**Comment by mikko-apo** [comment]
Accurate reading hasn't been my forte :) I just noticed that the various modules listed in the beginning of http://www.rapidoid.org/ mention that only JDK 6-8 is supported.

JDK9 support would be a nice addition since JDK9 has been out 3 months.

**Comment by nmihajlovski** [comment]
Hi, I am closing this now. Please take a look at #176
