### ISSUE TITLE
Getting "HEADERS[Referer] must NOT be null!"

### ISSUE THREAD

**Issue by hboelke** [rapidoid/rapidoid#161]
Im getting the following exception / 500 Response when calling the GET /_logout 

> HEADERS[Referer] must NOT be null!

```
java.lang.IllegalArgumentException: HEADERS[Referer] must NOT be null!
	at org.rapidoid.u.U.illegal(U.java:443)
	at org.rapidoid.u.U.notNull(U.java:490)
	at org.rapidoid.http.impl.ReqImpl.header(ReqImpl.java:304)
	at org.rapidoid.goodies.LogoutHandler.execute(LogoutHandler.java:39)
	at org.rapidoid.goodies.LogoutHandler.execute(LogoutHandler.java:32)
	at org.rapidoid.http.handler.optimized.DelegatingParamsAwareReqRespHandler.handleReq(DelegatingParamsAwareReqRespHandler.java:49)
	at org.rapidoid.http.handler.AbstractHttpHandlerDecorator.handleReqAndPostProcess(AbstractHttpHandlerDecorator.java:48)
	at org.rapidoid.http.handler.HttpManagedHandlerDecorator$3.invokeNext(HttpManagedHandlerDecorator.java:161)
	at org.rapidoid.http.handler.HttpManagedHandlerDecorator$3.invoke(HttpManagedHandlerDecorator.java:121)
	at org.rapidoid.http.handler.HttpAuthWrapper.wrap(HttpAuthWrapper.java:70)
	at org.rapidoid.http.handler.HttpManagedHandlerDecorator.wrap(HttpManagedHandlerDecorator.java:185)
	at org.rapidoid.http.handler.HttpManagedHandlerDecorator.handleWithWrappers(HttpManagedHandlerDecorator.java:100)
	at org.rapidoid.http.handler.HttpManagedHandlerDecorator.access$200(HttpManagedHandlerDecorator.java:39)
	at org.rapidoid.http.handler.HttpManagedHandlerDecorator$2.run(HttpManagedHandlerDecorator.java:83)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

This only happens if i called the POST /_login route before.
And the first GET /_logout request, after login throws an exception.
Every GET /_logout request after that returns 403 Forbidden

Reproduce:

> Login using the POST /_login route
> Logout using the GET /_logout route

**Comment by hboelke** [comment]
Looks like this is the desired result

```java
	@Override
	public Object execute(Req req, Resp resp) throws Exception {
		resp.logout();
		return resp.redirect(req.header(Headers.REFERER));
	}

```

Not sure why this happens tho, my requests are stateless.

**Comment by nmihajlovski** [comment]
Thanks for reporting this. I will fix it to make the redirect optional (to redirect only If the referrer is provided).
