### ISSUE TITLE
Error occurred when handling request! | error = java.lang.NullPointerException

### ISSUE THREAD

**Issue by vuminhngoc** [rapidoid/rapidoid#178]
When running webservice with rapidoid about 2 days, this errors appear:
 Error occurred when handling request! | error = java.lang.NullPointerException
java.lang.NullPointerException
 2018-10-13 09:15:24
 org.rapidoid.log.Log[383] -
                                Caller+0         at org.rapidoid.log.Log.log(Log.java:383)
Caller+1         at org.rapidoid.log.Log.log(Log.java:491)
Caller+2         at org.rapidoid.http.impl.lowlevel.LowLevelHttpIO.logError(LowLevelHttpIO.java:218)
Caller+3         at org.rapidoid.http.impl.lowlevel.LowLevelHttpIO.error(LowLevelHttpIO.java:188)
Caller+4         at org.rapidoid.http.impl.lowlevel.HttpIO.error(HttpIO.java:62)
Caller+5         at org.rapidoid.http.handler.HttpManagedHandlerDecorator.handleError(HttpManagedHandlerDecorator.java:192)
Caller+6         at org.rapidoid.http.handler.HttpManagedHandlerDecorator.complete(HttpManagedHandlerDecorator.java:205)
Caller+7         at org.rapidoid.http.handler.HttpManagedHandlerDecorator.handleWithWrappers(HttpManagedHandlerDecorator.java:109)

Can i disable logs of rapidroid?

**Comment by nmihajlovski** [comment]
Hi, without a proper way to reproduce this problem, I can't know what happens, and if there is a bug in Rapidoid or your application caused this.

You could set the logging level to `LogLevel.NO_LOGS`, but I don't recommend ignoring the problem.

**Comment by vuminhngoc** [comment]
I seted disable log but not work.
Log.setLogLevel(LogLevel.NO_LOGS);

I can't log any requests cause this error, I wasn't use logging when handle requests. And fisrt caller (HttpManagedHandlerDecorator.java:109) not from my app, so i can't trace back error.
