### ISSUE TITLE
On.page().mvc() error

### ISSUE THREAD

**Issue by danuvian** [rapidoid/rapidoid#201]
I am trying to copy your examples for displaying an HTML page and I am getting an error.

I have code like this:

On.page("/hi").mvc("Hello <b>world</b>!");

And I have a "hi.html" file in resources/templates.

11:32:10.236 [executor1] ERROR o.r.h.impl.lowlevel.LowLevelHttpIO - Error occurred when handling request! | error = java.lang.RuntimeException: Error while retrieving view: hi
java.lang.RuntimeException: Error while retrieving view: hi
        at org.rapidoid.u.U.rte(U.java:427)
        at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:117)
        at org.rapidoid.http.impl.ResponseRenderer.renderMvc(ResponseRenderer.java:57)
        at org.rapidoid.http.impl.BodyRenderer.createRespBodyFromResult(BodyRenderer.java:67)
        at org.rapidoid.http.impl.BodyRenderer.toRespBody(BodyRenderer.java:41)
        at org.rapidoid.http.impl.ReqImpl.renderResponse(ReqImpl.java:569)
        at org.rapidoid.http.impl.ReqImpl.renderResponseOrError(ReqImpl.java:549)
        at org.rapidoid.http.impl.ReqImpl.onDone(ReqImpl.java:524)
        at org.rapidoid.http.impl.ReqImpl.done(ReqImpl.java:510)
        at org.rapidoid.http.handler.HttpManagedHandlerDecorator.processNormalResult(HttpManagedHandlerDecorator.java:232)
        at org.rapidoid.http.handler.HttpManagedHandlerDecorator.complete(HttpManagedHandlerDecorator.java:223)
        at org.rapidoid.http.handler.HttpManagedHandlerDecorator.handleWithWrappers(HttpManagedHandlerDecorator.java:109)
        at org.rapidoid.http.handler.HttpManagedHandlerDecorator.access$200(HttpManagedHandlerDecorator.java:39)
        at org.rapidoid.http.handler.HttpManagedHandlerDecorator$2.run(HttpManagedHandlerDecorator.java:83)
        at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Couldn't recalculate the cache value!
        at org.rapidoid.u.U.rte(U.java:427)
        at org.rapidoid.cache.impl.ConcurrentCacheAtom.retrieveCachedValue(ConcurrentCacheAtom.java:163)
        at org.rapidoid.cache.impl.ConcurrentCacheAtom.get(ConcurrentCacheAtom.java:64)
        at org.rapidoid.cache.impl.ConcurrentCache.get(ConcurrentCache.java:175)
        at org.rapidoid.render.RapidoidTemplateFactory.load(RapidoidTemplateFactory.java:66)
        at org.rapidoid.http.customize.defaults.DefaultViewResolver.getView(DefaultViewResolver.java:49)
        at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:115)
        ... 16 more
Caused by: java.lang.RuntimeException: 
        at org.rapidoid.u.U.rte(U.java:427)
        at org.rapidoid.u.U.rte(U.java:431)
        at org.rapidoid.render.TemplateCompiler.compile(TemplateCompiler.java:49)
        at org.rapidoid.render.XNode.compile(XNode.java:63)
        at org.rapidoid.render.XNode.compile(XNode.java:67)
        at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:83)
        at org.rapidoid.render.RapidoidTemplateFactory.loadAndCompile(RapidoidTemplateFactory.java:40)
        at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:54)
        at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:51)
        at org.rapidoid.cache.impl.ConcurrentCacheAtom.retrieveCachedValue(ConcurrentCacheAtom.java:130)
        ... 21 more
Caused by: javassist.NotFoundException: org.rapidoid.render.TemplateRenderer
        at javassist.ClassPool.get(ClassPool.java:450)
        at org.rapidoid.render.TemplateCompiler.tryToCompile(TemplateCompiler.java:60)
        at org.rapidoid.render.TemplateCompiler.compile(TemplateCompiler.java:46)
        ... 28 more

**Comment by desmond27** [comment]
I've been facing the same issue. But it looks like this project has been dead for a good portion of three years.
