### ISSUE TITLE
DATA[arg2] must NOT be null

### ISSUE THREAD

**Issue by hasanb** [rapidoid/rapidoid#65]
@GET
	public String example(double lorem, double ipsum) {
		return "test";
	}
If I do GET /example?lorem=1.0&ipsum=2.0 with the code above, everything is fine.

	@GET
	public String example(double lorem, double ipsum, double dolor) {
		return "test";
	}
Now if I add a third parameter and do GET /example?lorem=1.0&ipsum=2.0&dolor=3.0 it raises an exception:

	java.lang.IllegalArgumentException: DATA[arg2] must NOT be null!
	at org.rapidoid.u.U.illegal(U.java:386)
	at org.rapidoid.u.U.notNull(U.java:433)
	at org.rapidoid.http.impl.ReqImpl.data(ReqImpl.java:315)
	at org.rapidoid.http.handler.param.DataParamRetriever.getParamValue(DataParamRetriever.java:43)
	at org.rapidoid.http.handler.lambda.NParamMethodHandler.arg(NParamMethodHandler.java:78)
	at org.rapidoid.http.handler.lambda.NParamMethodHandler.args(NParamMethodHandler.java:85)
	at org.rapidoid.http.handler.MethodReqHandler.handleReq(MethodReqHandler.java:48)
	at org.rapidoid.http.handler.AbstractAsyncHttpHandler$1.run(AbstractAsyncHttpHandler.java:154)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

However, if I do GET /example?lorem=1.0&ipsum=2.0&arg2=3.0, everything is fine. So any third parameter gets renamed to arg2. Is this the expected behaviour?

Same goes for situations where the URL is specified in GET, for example when I do:
GET /example/1.0/2.0/3.0
it does not work with `@GET("/example/{lorem}/{ipsum}/{dolor}")`
it does work with `@GET("/example/{lorem}/{ipsum}/{arg2}")`

I am using the latest Maven version
`<dependency>
<groupId>org.rapidoid</groupId>
<artifactId>rapidoid-quick</artifactId>
<version>5.1.4</version>
</dependency>`

**Comment by nmihajlovski** [comment]
Hi Hasan, thanks for reporting this, I reproduced the bug and I will try to fix it ASAP...

**Comment by nmihajlovski** [comment]
Retrieving the param names is tricky and it is the root of this bug. In a meantime, annotating the param as `@Param("dolor") double dolor` will solve the problem.

**Comment by hasanb** [comment]
Thanks for your fast response and the cool framework. Looking forward for the next version.

**Comment by nmihajlovski** [comment]
I released v5.1.5 with the fix, should be available soon on Maven Central.

**Comment by nmihajlovski** [comment]
Hi, can you please confirm the fix, so I can close this issue? (And thanks!) :)
