### ISSUE TITLE
Unable to visit admin center on windows

### ISSUE THREAD

**Issue by sagnitude** [rapidoid/rapidoid#87]
I started a simple server with rapidoid-web version 5.2.0 on a windows machine:

```
public class RapidoidRunner {

    public static void main(String[] args) {
        App.bootstrap().adminCenter();
    }
}
```

But when I tried to open `http://localhost:8888` in browser, the following exceptions are thrown:

```
ERROR | executor2 | org.rapidoid.http.impl.HttpIO | Error occurred when handling request! | error = java.lang.RuntimeException: Error while rendering view: 404
java.lang.RuntimeException: Error while rendering view: 404
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:118)
	at org.rapidoid.http.impl.ResponseRenderer.render(ResponseRenderer.java:55)
	at org.rapidoid.http.impl.RespImpl.renderToBytes(RespImpl.java:472)
	at org.rapidoid.http.impl.ReqImpl.responseToBytes(ReqImpl.java:553)
	at org.rapidoid.http.impl.ReqImpl.renderResponse(ReqImpl.java:538)
	at org.rapidoid.http.impl.ReqImpl.renderResponseOrError(ReqImpl.java:524)
	at org.rapidoid.http.impl.ReqImpl.onDone(ReqImpl.java:505)
	at org.rapidoid.http.impl.ReqImpl.done(ReqImpl.java:493)
	at org.rapidoid.http.impl.HttpIO$1.run(HttpIO.java:218)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
......
```

It works on mac osx. This problem might be relevant to #62 .

Detailed log:

```
"C:\Program Files\Java\jdk1.8.0_11\bin\java" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:15487,suspend=y,server=n -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_11\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\zipfs.jar;D:\Workspace\gitrepos\RapidoidTest\target\classes;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-web\5.2.0\rapidoid-web-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-gui\5.2.0\rapidoid-gui-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-html\5.2.0\rapidoid-html-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-render\5.2.0\rapidoid-render-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-jpa\5.2.0\rapidoid-jpa-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-http-server\5.2.0\rapidoid-http-server-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-http-fast\5.2.0\rapidoid-http-fast-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-net\5.2.0\rapidoid-net-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-buffer\5.2.0\rapidoid-buffer-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-inject\5.2.0\rapidoid-inject-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-http-client\5.2.0\rapidoid-http-client-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-commons\5.2.0\rapidoid-commons-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-essentials\5.2.0\rapidoid-essentials-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\javassist\javassist\3.20.0-GA\javassist-3.20.0-GA.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.6.6\jackson-databind-2.6.6.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.6.0\jackson-annotations-2.6.0.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.6.6\jackson-core-2.6.6.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\module\jackson-module-afterburner\2.6.6\jackson-module-afterburner-2.6.6.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.6.6\jackson-dataformat-yaml-2.6.6.jar;C:\Users\Administrator\.m2\repository\org\yaml\snakeyaml\1.15\snakeyaml-1.15.jar;C:\Users\Administrator\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpasyncclient\4.1\httpasyncclient-4.1.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpcore\4.4.1\httpcore-4.4.1.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpcore-nio\4.4.1\httpcore-nio-4.4.1.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpclient\4.4.1\httpclient-4.4.1.jar;C:\Users\Administrator\.m2\repository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\Administrator\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\Administrator\.m2\repository\org\apache\httpcomponents\httpmime\4.5\httpmime-4.5.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-watch\5.2.0\rapidoid-watch-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-integrate\5.2.0\rapidoid-integrate-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\rapidoid\rapidoid-oauth\5.2.0\rapidoid-oauth-5.2.0.jar;C:\Users\Administrator\.m2\repository\org\apache\oltu\oauth2\org.apache.oltu.oauth2.client\1.0.1\org.apache.oltu.oauth2.client-1.0.1.jar;C:\Users\Administrator\.m2\repository\org\apache\oltu\oauth2\org.apache.oltu.oauth2.common\1.0.1\org.apache.oltu.oauth2.common-1.0.1.jar;C:\Users\Administrator\.m2\repository\org\json\json\20140107\json-20140107.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-api\1.7.7\slf4j-api-1.7.7.jar;C:\Users\Administrator\.m2\repository\com\google\code\gson\gson\2.6.2\gson-2.6.2.jar;C:\Users\Administrator\.m2\repository\com\googlecode\json-simple\json-simple\1.1.1\json-simple-1.1.1.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1\lib\idea_rt.jar" org.test.RapidoidRunner
Connected to the target VM, address: '127.0.0.1:15487', transport: 'socket'
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
INFO | main | org.rapidoid.config.RapidoidInitializer | Starting Rapidoid... | version = 5.2.0 | process = 16992@sagnitude-PC | java = 1.8.0_11 | dir = D:\Workspace\gitrepos\RapidoidTest
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO | main | org.rapidoid.setup.App | Inferring application root | main = org.test.RapidoidRunner | package = org.test
INFO | main | org.rapidoid.scan.ClasspathUtil | Scanning classpath | annotated = [@Controller, @Service, @Run, @Named, @Singleton] | packages = [org.test]
INFO | main | org.rapidoid.scan.ClasspathUtil | Finished classpath scan | time = 181ms | searched = 2 | found = []
INFO | main | org.rapidoid.commons.Environment | No profiles were specified, activating 'default' profile
INFO | main | org.rapidoid.commons.Environment | No production/dev/test mode was configured, inferring mode | mode = DEV
INFO | main | org.rapidoid.commons.Environment | Initialized environment | mode = DEV | profiles = [default, dev]
INFO | main | org.rapidoid.config.ConfigImpl | Loaded configuration | files = [default-config.yml, default-config-default.yml, default-config-dev.yml, default-config.yml, default-config-default.yml, default-config-dev.yml]
INFO | main | org.rapidoid.util.Msc | --------------------------
INFO | main | org.rapidoid.util.Msc | Registering Admin goodies:
INFO | main | org.rapidoid.util.Msc | --------------------------
INFO | main | org.rapidoid.insight.Metrics | Bootstraping metrics
INFO | main | org.rapidoid.setup.WatchForChanges | Watching classpath for changes... | classpath = [D:\Workspace\gitrepos\RapidoidTest\target\classes]
INFO | server | org.rapidoid.net.impl.RapidoidServerLoop | Starting server | address = 0.0.0.0 | port = 8888 | I/O workers = 8 | accept = non-blocking
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_ | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/entities | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/routes | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/beans | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/config | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/jmx/memory | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/jmx/mempool | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/jmx/classes | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/jmx/os | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/jmx/threads | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/jmx/compilation | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/jmx/runtime | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/jmx/gc | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/metrics | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET | path = /_/graphs/{id:.*} | roles = [administrator] | tx = NONE | mvc = false
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET | path = /_/classpath | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/deploy | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = POST | path = /_/jar | roles = [administrator] | tx = NONE | mvc = false
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET,POST | path = /_/terminate | roles = [administrator] | tx = NONE | mvc = true
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET | path = /_ping | roles = [administrator] | tx = NONE | mvc = false
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = POST | path = /_login | roles = [] | tx = NONE | mvc = false
INFO | main | org.rapidoid.http.impl.HttpRoutesImpl | Registering handler | setup = admin | verbs = GET | path = /_logout | roles = [logged_in] | tx = NONE | mvc = false
INFO | main | org.rapidoid.util.Msc | ------------------------------------------------------------------------------------------------
INFO | main | org.rapidoid.util.Msc | ADMIN CREDENTIALS: username = admin, password = 6C30BB89ADB32C5600DCEC2A6CD825C7
INFO | main | org.rapidoid.util.Msc | ------------------------------------------------------------------------------------------------
ERROR | executor2 | org.rapidoid.http.impl.HttpIO | Error occurred when handling request! | error = java.lang.RuntimeException: Error while rendering view: 404
java.lang.RuntimeException: Error while rendering view: 404
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:118)
	at org.rapidoid.http.impl.ResponseRenderer.render(ResponseRenderer.java:55)
	at org.rapidoid.http.impl.RespImpl.renderToBytes(RespImpl.java:472)
	at org.rapidoid.http.impl.ReqImpl.responseToBytes(ReqImpl.java:553)
	at org.rapidoid.http.impl.ReqImpl.renderResponse(ReqImpl.java:538)
	at org.rapidoid.http.impl.ReqImpl.renderResponseOrError(ReqImpl.java:524)
	at org.rapidoid.http.impl.ReqImpl.onDone(ReqImpl.java:505)
	at org.rapidoid.http.impl.ReqImpl.done(ReqImpl.java:493)
	at org.rapidoid.http.impl.HttpIO$1.run(HttpIO.java:218)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: 
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.u.U.rte(U.java:420)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:52)
	at org.rapidoid.render.RapidoidTemplateFactory.load(RapidoidTemplateFactory.java:60)
	at org.rapidoid.render.RenderCtxImpl.call(RenderCtxImpl.java:138)
	at RapidoidTemplate1.render(RapidoidTemplate1.java)
	at org.rapidoid.render.RapidoidTemplate.doRender(RapidoidTemplate.java:65)
	at org.rapidoid.render.RapidoidTemplate.renderTo(RapidoidTemplate.java:87)
	at org.rapidoid.http.customize.defaults.DefaultViewResolver$1.render(DefaultViewResolver.java:58)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:115)
	... 12 more
Caused by: java.lang.RuntimeException: Couldn't load template: page-segments/page-globals.html
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:74)
	at org.rapidoid.render.RapidoidTemplateFactory.loadAndCompile(RapidoidTemplateFactory.java:44)
	at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:39)
	at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:36)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:50)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Invalid resource name: page-segments\page-globals.html
	at org.rapidoid.u.U.illegal(U.java:432)
	at org.rapidoid.u.U.must(U.java:458)
	at org.rapidoid.io.Res.validateFilename(Res.java:85)
	at org.rapidoid.io.Res.<init>(Res.java:81)
	at org.rapidoid.io.Res.create(Res.java:139)
	at org.rapidoid.io.Res.relative(Res.java:126)
	at org.rapidoid.io.Res.from(Res.java:90)
	at org.rapidoid.io.Res.from(Res.java:94)
	at org.rapidoid.http.customize.defaults.DefaultTemplateLoader.load(DefaultTemplateLoader.java:43)
	at org.rapidoid.http.customize.defaults.DefaultViewResolver$2.loadTemplate(DefaultViewResolver.java:67)
	at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:72)
	... 23 more

java.lang.RuntimeException: Error while rendering view: error
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:118)
	at org.rapidoid.http.impl.ResponseRenderer.render(ResponseRenderer.java:55)
	at org.rapidoid.http.impl.RespImpl.renderToBytes(RespImpl.java:472)
	at org.rapidoid.http.impl.ReqImpl.responseToBytes(ReqImpl.java:559)
	at org.rapidoid.http.impl.ReqImpl.renderResponse(ReqImpl.java:538)
	at org.rapidoid.http.impl.ReqImpl.renderResponseOrError(ReqImpl.java:524)
	at org.rapidoid.http.impl.ReqImpl.onDone(ReqImpl.java:505)
	at org.rapidoid.http.impl.ReqImpl.done(ReqImpl.java:493)
	at org.rapidoid.http.impl.HttpIO$1.run(HttpIO.java:218)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: 
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.u.U.rte(U.java:420)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:52)
	at org.rapidoid.render.RapidoidTemplateFactory.load(RapidoidTemplateFactory.java:60)
	at org.rapidoid.render.RenderCtxImpl.call(RenderCtxImpl.java:138)
	at RapidoidTemplate2.render(RapidoidTemplate2.java)
	at org.rapidoid.render.RapidoidTemplate.doRender(RapidoidTemplate.java:65)
	at org.rapidoid.render.RapidoidTemplate.renderTo(RapidoidTemplate.java:87)
	at org.rapidoid.http.customize.defaults.DefaultViewResolver$1.render(DefaultViewResolver.java:58)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:115)
	... 12 more
Caused by: java.lang.RuntimeException: Couldn't load template: page-segments/page-globals.html
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:74)
	at org.rapidoid.render.RapidoidTemplateFactory.loadAndCompile(RapidoidTemplateFactory.java:44)
	at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:39)
	at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:36)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:50)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Invalid resource name: page-segments\page-globals.html
	at org.rapidoid.u.U.illegal(U.java:432)
	at org.rapidoid.u.U.must(U.java:458)
	at org.rapidoid.io.Res.validateFilename(Res.java:85)
	at org.rapidoid.io.Res.<init>(Res.java:81)
	at org.rapidoid.io.Res.create(Res.java:139)
	at org.rapidoid.io.Res.relative(Res.java:126)
	at org.rapidoid.io.Res.from(Res.java:90)
	at org.rapidoid.io.Res.from(Res.java:94)
	at org.rapidoid.http.customize.defaults.DefaultTemplateLoader.load(DefaultTemplateLoader.java:43)
	at org.rapidoid.http.customize.defaults.DefaultViewResolver$2.loadTemplate(DefaultViewResolver.java:67)
	at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:72)
	... 23 more
ERROR | executor2 | org.rapidoid.http.impl.ReqImpl | Internal rendering error! | message = Error while rendering view: error
ERROR | executor3 | org.rapidoid.http.impl.HttpIO | Error occurred when handling request! | error = java.lang.RuntimeException: Error while rendering view: 404
java.lang.RuntimeException: Error while rendering view: 404
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:118)
	at org.rapidoid.http.impl.ResponseRenderer.render(ResponseRenderer.java:55)
	at org.rapidoid.http.impl.RespImpl.renderToBytes(RespImpl.java:472)
	at org.rapidoid.http.impl.ReqImpl.responseToBytes(ReqImpl.java:553)
	at org.rapidoid.http.impl.ReqImpl.renderResponse(ReqImpl.java:538)
	at org.rapidoid.http.impl.ReqImpl.renderResponseOrError(ReqImpl.java:524)
	at org.rapidoid.http.impl.ReqImpl.onDone(ReqImpl.java:505)
	at org.rapidoid.http.impl.ReqImpl.done(ReqImpl.java:493)
	at org.rapidoid.http.impl.HttpIO$1.run(HttpIO.java:218)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: 
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.u.U.rte(U.java:420)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:52)
	at org.rapidoid.render.RapidoidTemplateFactory.load(RapidoidTemplateFactory.java:60)
	at org.rapidoid.render.RenderCtxImpl.call(RenderCtxImpl.java:138)
	at RapidoidTemplate1.render(RapidoidTemplate1.java)
	at org.rapidoid.render.RapidoidTemplate.doRender(RapidoidTemplate.java:65)
	at org.rapidoid.render.RapidoidTemplate.renderTo(RapidoidTemplate.java:87)
	at org.rapidoid.http.customize.defaults.DefaultViewResolver$1.render(DefaultViewResolver.java:58)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:115)
	... 12 more
Caused by: java.lang.RuntimeException: Couldn't load template: page-segments/page-globals.html
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:74)
	at org.rapidoid.render.RapidoidTemplateFactory.loadAndCompile(RapidoidTemplateFactory.java:44)
	at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:39)
	at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:36)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:50)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Invalid resource name: page-segments\page-globals.html
	at org.rapidoid.u.U.illegal(U.java:432)
	at org.rapidoid.u.U.must(U.java:458)
	at org.rapidoid.io.Res.validateFilename(Res.java:85)
	at org.rapidoid.io.Res.<init>(Res.java:81)
	at org.rapidoid.io.Res.create(Res.java:139)
	at org.rapidoid.io.Res.relative(Res.java:126)
	at org.rapidoid.io.Res.from(Res.java:90)
	at org.rapidoid.io.Res.from(Res.java:94)
	at org.rapidoid.http.customize.defaults.DefaultTemplateLoader.load(DefaultTemplateLoader.java:43)
	at org.rapidoid.http.customize.defaults.DefaultViewResolver$2.loadTemplate(DefaultViewResolver.java:67)
	at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:72)
	... 23 more

ERROR | executor3 | org.rapidoid.http.impl.ReqImpl | Internal rendering error! | message = Error while rendering view: error
java.lang.RuntimeException: Error while rendering view: error
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:118)
	at org.rapidoid.http.impl.ResponseRenderer.render(ResponseRenderer.java:55)
	at org.rapidoid.http.impl.RespImpl.renderToBytes(RespImpl.java:472)
	at org.rapidoid.http.impl.ReqImpl.responseToBytes(ReqImpl.java:559)
	at org.rapidoid.http.impl.ReqImpl.renderResponse(ReqImpl.java:538)
	at org.rapidoid.http.impl.ReqImpl.renderResponseOrError(ReqImpl.java:524)
	at org.rapidoid.http.impl.ReqImpl.onDone(ReqImpl.java:505)
	at org.rapidoid.http.impl.ReqImpl.done(ReqImpl.java:493)
	at org.rapidoid.http.impl.HttpIO$1.run(HttpIO.java:218)
	at org.rapidoid.job.PredefinedContextJobWrapper.run(PredefinedContextJobWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: 
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.u.U.rte(U.java:420)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:52)
	at org.rapidoid.render.RapidoidTemplateFactory.load(RapidoidTemplateFactory.java:60)
	at org.rapidoid.render.RenderCtxImpl.call(RenderCtxImpl.java:138)
	at RapidoidTemplate2.render(RapidoidTemplate2.java)
	at org.rapidoid.render.RapidoidTemplate.doRender(RapidoidTemplate.java:65)
	at org.rapidoid.render.RapidoidTemplate.renderTo(RapidoidTemplate.java:87)
	at org.rapidoid.http.customize.defaults.DefaultViewResolver$1.render(DefaultViewResolver.java:58)
	at org.rapidoid.http.impl.ResponseRenderer.renderView(ResponseRenderer.java:115)
	... 12 more
Caused by: java.lang.RuntimeException: Couldn't load template: page-segments/page-globals.html
	at org.rapidoid.u.U.rte(U.java:416)
	at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:74)
	at org.rapidoid.render.RapidoidTemplateFactory.loadAndCompile(RapidoidTemplateFactory.java:44)
	at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:39)
	at org.rapidoid.render.RapidoidTemplateFactory$1.map(RapidoidTemplateFactory.java:36)
	at org.rapidoid.collection.AutoExpandingMap.get(AutoExpandingMap.java:50)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Invalid resource name: page-segments\page-globals.html
	at org.rapidoid.u.U.illegal(U.java:432)
	at org.rapidoid.u.U.must(U.java:458)
	at org.rapidoid.io.Res.validateFilename(Res.java:85)
	at org.rapidoid.io.Res.<init>(Res.java:81)
	at org.rapidoid.io.Res.create(Res.java:139)
	at org.rapidoid.io.Res.relative(Res.java:126)
	at org.rapidoid.io.Res.from(Res.java:90)
	at org.rapidoid.io.Res.from(Res.java:94)
	at org.rapidoid.http.customize.defaults.DefaultTemplateLoader.load(DefaultTemplateLoader.java:43)
	at org.rapidoid.http.customize.defaults.DefaultViewResolver$2.loadTemplate(DefaultViewResolver.java:67)
	at org.rapidoid.render.RapidoidTemplateFactory.loadTemplate(RapidoidTemplateFactory.java:72)
	... 23 more
```

**Comment by shoon** [comment]
Just in general the "**Invalid resource name: page-segments\page-globals.html**" has caused our app to stop working when we transitioned from 5.1.9 -> 5.2.0. 

We reverted back to **5.1.9** and all is fine.
